apiVersion: eksctl.io/v1alpha5

kind: ClusterConfig

metadata:
  name: groupone

  region: us-east-1

vpc:
  id: vpc-0599f1240421d250b

  cidr: "192.168.0.0/16"

  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-0bf97b425adbc648f

      my-new-stack-PublicSubnet02:
        id: subnet-03530cc517c008b18

    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-09d49968e9a239c08

      my-new-stack-PrivateSubnet02:
        id: subnet-08b9d014f18f9693b

nodeGroups:
  - name: EKS-public-workers

    instanceType: t2.micro

    desiredCapacity: 2

  - name: EKS-private-workers

    instanceType: t2.micro

    desiredCapacity: 1

    privateNetworking: true
